import Head from 'next/head'
import styles from '/styles/Home.module.css'
import { Footer } from '/components/organisms/Footer/Footer.js'
import { Links } from '/components/organisms/Links/Links.js'
import { Headline } from '/components/organisms/Headline/Headline.js'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>About</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Headline page="about" />
        <Links />
      </main>
      <Footer />
    </div>
  )
}
